# Generated by Django 4.0.4 on 2022-06-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=255)),
                ('location', models.TextField()),
                ('created_on', models.TimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('updated_on', models.TimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
