# Generated by Django 4.0.4 on 2022-06-07 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='created_by',
            field=models.ForeignKey(max_length=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creater_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seller',
            name='updated_by',
            field=models.ForeignKey(max_length=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updater_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
