# Generated by Django 4.0.4 on 2022-06-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_seller_created_by_alter_seller_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
