# Generated by Django 4.0.4 on 2022-06-07 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicine.medicine'),
        ),
    ]
