# Generated by Django 4.0.4 on 2022-06-07 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('seller', 'medicine')},
        ),
    ]
