# Generated by Django 4.0.4 on 2022-06-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_on', models.TimeField(auto_now_add=True)),
                ('updated_on', models.TimeField(auto_now=True)),
            ],
        ),
    ]
