# Generated by Django 4.0.4 on 2022-06-07 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalCompound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_on', models.TimeField(auto_now_add=True)),
                ('updated_on', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('max_price', models.IntegerField()),
                ('usage', models.CharField(blank=True, max_length=255, null=True)),
                ('dose', models.CharField(blank=True, max_length=255, null=True)),
                ('prescription', models.BooleanField(blank=True, null=True)),
                ('max_selling_quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.TimeField(auto_now_add=True)),
                ('updated_on', models.TimeField(auto_now=True)),
                ('chemical_compound', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicine.chemicalcompound')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
            ],
        ),
    ]
